##' Print parameter table to console, flextable, latex, or (latex) pdf file
##' @param pars A parameter table as generated by `NMwork::createParameterTable()`.
##' @param include.fix Either a logical or "NotZero". `TRUE` means fixed parameters are not filtered out, `FALSE` means they are filtered out, "NotZero" means they are only kept if not equal to zero.
##' @param include A character vector of symbol values to include. All else will be dropped.
##' @param include.pattern A regular expression run on the `symbol` column. What matches will be kept. 
##' @param drop A character vector of symbol values to drop. All else will be kept.
##' @param drop.pattern A regular expression run on the `symbol` column. What matches will be dropped. 
##' @import data.table
##' @import flextable
##' @import ftExtra
##' @import kableExtra
##' @importFrom dplyr group_by
##' @examples
##' file.mod <- system.file("nonmem/xgxr134.mod",package="NMwork")
##' pars <- createParameterTable(file.lst=file.mod,
##'                   args.ParsText=list(format="%idx; %symbol ; %label [%unit] ; %trans",
##'                                      format.sigma="%symbol - %label "))
##' printParameterTable(pars=pars,format="R")
##' printParameterTable(pars=pars,format="rmd")
##' @export
##'

## todo

### for rmd and rmd-latex: can't get longtable to work with
### footnotes. Currently not using footnotes.

### no current way to generate rmd-pdf using kable, now defaults to using pmtables

printParameterTable <- function(pars,engine="kable",format,footnotes=NULL,script=NULL,file.mod,include,include.pattern,drop,drop.pattern,include.fix,caption){

    if(missing(drop)) drop <- NULL
    if(missing(drop.pattern)) drop.pattern <- NULL
    if(missing(include)) include <- NULL
    if(missing(include.fix)) include.fix <- TRUE
    if(missing(include.pattern)) include.pattern <- NULL
    
    ##paramtbl <- readRDS(file.rds)
    paramtbl <- pars
    info.source <- NMinfo(paramtbl)
    model <- NULL

    ### only one format at a time supported
    
    if(missing(format)) format <- NULL

    if(length(engine)>1) stop("Only one engine can be used at a time")
    engine <- tolower(NMdata:::cleanSpaces(engine))
    if(!engine %in% c("kable","pmtables","flextable")) stop("engine must be either kable, flextable, or pmtables.")

    if(is.null(format)){
        format <- switch(engine,
                         pmtables="latex",
                         kable="r",
                         flextable="ft")
    }


    if(engine=="kable"){
        if(is.null(format)){
            format <- "r"
        }
    }

    compile.pdf <- FALSE
    file.pdf <- NULL

    if(tolower(NMdata:::cleanSpaces(format)=="pdf") ){
        ### this is currently not supported for kable 
        file.pdf <- NULL
        format <- "latex"
        compile.pdf <- TRUE
    }

    ### this must happen before any modification of format to not edit a file name    
    if(tolower(fnExtension(format)=="pdf") ){
        file.pdf <- format
        format <- "latex"
        compile.pdf <- TRUE
    }

    format <- tolower(format)
    format <- NMdata:::cleanSpaces(format)

    if(length(format)>1) stop("Only one format can be specified.")
    # if(!format %in% c("r","html","flextable","latex","rmd-pdf","pdf","kable-rmd","kable-rmd-pdf")) {
    #     stop("format must be one of R, flextable, rmd, or a path to a file with extension .pdf.")
    # }

    fixUnder <- ifelse(format%in%c("latex"),
                       function(x)gsub("\\_","\\\\_",x),
                       identity)

    if( !missing(file.mod) && !is.null(file.mod) ){
        model <- modelPaths(file.mod)
    } else if(!is.null(info.source$dataCreate$model)){
        model <- modelPaths(info.source$dataCreate$model)
    }

    ### this is a header
        string.caption <- paste("Model: ",fixUnder(model$run))
    if(!missing(caption)){
        string.caption <- paste(paste(caption,collapse=" ")
                               ,string.caption,
                                sep=". "
                                )
    }

    footnotes <- c(footnotes,
                   "* parameter was estimated in the log domain and back-transformed for clarity.",
                   "RSE: Relative Standard Error on the scale where the parameter was estimated.")

    if(!is.null(script)){
        footnotes <- c(footnotes,sprintf("Source: %s",fixUnder(script)))
    }
    if(!is.null(model)){
        footnotes <- c(footnotes,sprintf("Model: %s",fixUnder(model$label)))
    }


    ##### subset parameters
    if("symbol" %in% colnames(paramtbl)){
        if( !is.null(drop) ){
            paramtbl <- paramtbl[!symbol%in%drop]
        }
        if( !is.null(include) ){
            paramtbl <- paramtbl[symbol%in%include]
        }

        if(!is.null(drop.pattern)){
            paramtbl <- paramtbl[!grepl(pattern=drop.pattern,symbol,fix=FALSE)]
        }

        if(!is.null(include.pattern)){
            paramtbl <- paramtbl[!grepl(pattern=drop.pattern,symbol,fix=FALSE)]
        }
        
        if( is.logical(include.fix) && isFALSE(include.fix) ){
            paramtbl <- paramtbl[FIX==0|symbol%in%include]
        }
        
        if( !is.logical(include.fix) && tolower(include.fix)%in%c("ifnotzero", "notzero") ){
            paramtbl <- paramtbl[FIX==0|est!=0|symbol%in%include]
        }
    }



    if(engine=="kable"){
        ### not sure what formats are supported. At least latex, and html.

        if(format=="r"){
            paramtbl <- paramtbl[,.(
                "Parameter"=par.name,
                "Label"=tab.lab,
                "Est [CV% or Corr%] (RSE%)"=tab.est,
                "95% CI"=CI,
                Panel=panel
            )]
            
            lapply(footnotes,message)
            return(kable(paramtbl,format="pipe"))
        }

        ##
        nmbrows <- paramtbl[,.N,keyby=.(panel.label)]
        nmbrows[,start:=cumsum(shift(N,1,fill=0))+1]
        nmbrows[,end:=cumsum(N)]

        paramtbl2 <- paramtbl[,.(
            "  "=if(format=="latex") parameter.ltx else par.name,
            " "=if(format=="latex") tab.lab.ltx else tab.lab ,
            "Estimate (RSE\\%)\\newline[CV\\% or Corr\\%]"=
                if(format=="latex") tab.est.ltx else tab.est ,
            "95\\% Confidence Interval"=CI)]

        
        #### configure column justification and sizes. The widths are not automated.
        paramtbl2 <-
            paramtbl2 |>
            knitr::kable(
                       ## format = "latex",
                       format = format,
                       align = paste0("ll",paste(rep("c",times=(ncol(paramtbl2)-2)),collapse = "")),
                       caption = string.caption,
                       ## longtable=T,
                       booktabs=T, escape=F) |>
            #col.names = gsub("Description", " ", names(paramtbl))) |>
            kable_styling(full_width = T,
                          font_size = 7.5,  latex_options = "HOLD_position") |>
            column_spec(1, width="4em")|>
            column_spec(2, width = "26em") |>
            column_spec(3, width = "12em")

        
        ## for(I in 1:nrow(dt.panel)){
        for(I in 1:nrow(nmbrows)){
            paramtbl2 <- 
                nmbrows[I,pack_rows(paramtbl2,panel.label, start, end)]
        }

        ### Footnotes
        pars.ltx <- paramtbl2 |>
            add_footnote(label=footnotes,notation="none",escape=FALSE)

        if(!compile.pdf) return(pars.ltx)

        if(compile.pdf){
            if(is.null(file.pdf)) file.pdf <- tempfile(fileext=".pdf")
            ## "\\usepackage[margin=1in]{geometry}",
            latexStandAlone(pars.ltx,file.pdf=file.pdf,
                            usepackage=cc("geometry:margin=1in",
                                          booktabs,float,tabu,longtable
                                          ))
            ## return path to output?
            return(file.pdf)
        }
    }

    if(engine=="flextable"){

        paramtbl <- paramtbl[,.(
            "  "=par.name,
            " "=tab.lab,
            "Estimate (RSE%) [CV% or Corr%]"=tab.est,
            "95% Confidence Interval"=CI,
            panel.label)]

        paramtbl2 <- paramtbl |>
            dplyr::group_by(panel.label) ## |>
        ## slice(1, 2) |>
        ## select(-panel.label)

        ##as_flextable(hide_grouplabel = TRUE)
        ft <- as_flextable(paramtbl2,hide_grouplabel = TRUE) ##|> autofit()

        ft <- theme_vanilla(ft)
        ft <- add_footer_lines(ft, footnotes)
        ft <- color(ft, part = "footer", color = "#666666")
        ft <- fontsize(ft, part = "footer", size=10)
        ft <- align(ft, part="footer", align = "left")
        ft <- line_spacing(ft, space = 1, part = "footer")
        
        return(ft)
        
    }




    if(engine=="pmtables"){
                ## formats: latex, pdf, latex-pdf?

    loadres <- requireNamespace("pmtables",quietly=TRUE)
        if(!loadres) {
            stop("to use the pmtables format, pmtables must be installed. Find it on MPN.")
        }

        ##### TODO sorting should be handled independently of engine
        
        paramtbl2 <-
            paramtbl %>%
            dplyr::select(par.type, panel.label, i, j, parameter.ltx, tab.lab.ltx, tab.est.ltx, CI) %>%
            dplyr::arrange(panel.label, i, j) %>%
            dplyr::transmute(panel.label, parameter.ltx, tab.lab.ltx, tab.est.ltx, CI) %>%
            dplyr::mutate(rows.group = 1:dplyr::n(),.by=tab.lab.ltx) %>%
            dplyr::filter(rows.group==1) %>%
            dplyr::select(-rows.group)

        pars.ltx = 
            paramtbl2 %>%
            st_new() %>%
            st_panel("panel.label") %>%
            st_center(tab.lab.ltx = col_ragged(6.5)) %>%
            st_blank("parameter.ltx","tab.lab.ltx") %>%
            st_rename("Estimate (RSE\\%)...[CV\\% or Corr\\%]" = "tab.est.ltx",
                      "95\\% Confidence Interval" = "CI") %>%
            st_notes("$^*$Parameter was estimated in the log-domain and back-transformed for clarity") %>%
            st_notes("Abbreviations: RSE = relative standard error (on the scale where the parameter was estimated)") %>%
            st_notes(paste0("Model: ", model$mod)) %>%
            st_noteconf(type = "minipage", width = 1) 

        if( format=="latex" && !compile.pdf ) {
            ## create latex code. Don't compile.
            res <- pars.ltx %>% 
                st_make(long=TRUE)
            return(res)
        }
        
        if( format=="latex" && compile.pdf && is.null(file.pdf) ){
            ## Creating pdf in tmp location. 
            pars.ltx |>
                stable_long() |>
                st2report()
            ## what to return in this case?
            return(invisible(NULL))
        }

        if( format=="latex" && compile.pdf && !is.null(file.pdf) ){
            ## Creating pdf in named location. 
            ## This used to be format=="rmd-pdf"

            ## What is being returned?
            res <- pars.ltx |>
                stable_long() |>
                st2pdf(dir = dirname(file.pdf), stem = fnExtension(basename(file.pdf), "")) 
            return(res)
        }

    }
}
