##' Print parameter table to console, flextable, latex, or (latex) pdf file
##' @param pars A parameter table as generated by `NMwork::createParameterTable()`.
##' @param include.fix Either a logical or "ifNotZero". `TRUE` means fixed parameters are not filtered out, `FALSE` means they are filtered out, "ifNotZero" means they are only kept if not equal to zero.
##' @param include A character vector of symbol values to include. All else will be dropped.
##' @param include.pattern A regular expression run on the `symbol` column. What matches will be kept. 
##' @param drop A character vector of symbol values to drop. All else will be kept.
##' @param drop.pattern A regular expression run on the `symbol` column. What matches will be dropped. 
##' @import data.table
##' @import flextable
##' @import ftExtra
##' @import kableExtra
##' @importFrom dplyr group_by
##' @examples
##' file.mod <- system.file("nonmem/xgxr134.mod",package="NMwork")
##' pars <- createParameterTable(file.lst=file.mod,
##'                   args.ParsText=list(format="%idx; %symbol ; %label [%unit] ; %trans",
##'                                      format.sigma="%symbol - %label "))
##' printParameterTable(pars=pars,format="R")
##' printParameterTable(pars=pars,format="rmd")
##' @export
##'

## todo

### for rmd and rmd-latex: can't get longtable to work with
### footnotes. Currently not using footnotes.

printParameterTable <- function(pars,format,footnotes=NULL,script=NULL,file.mod,include,include.pattern,drop,drop.pattern,include.fix){

    if(missing(drop)) drop <- NULL
    if(missing(drop.pattern)) drop.pattern <- NULL
    if(missing(include)) include <- NULL
    if(missing(include.fix)) include.fix <- TRUE
    if(missing(include.pattern)) include.pattern <- NULL
    
    ##paramtbl <- readRDS(file.rds)
    paramtbl <- pars
    info.source <- NMinfo(paramtbl)
    model <- NULL

### only one format at a time supported
    
    if(tolower(fnExtension(format))=="pdf"){
        file.pdf <- format
        format <- "rmd-pdf"
    }
    
    format <- tolower(format)
    format <- NMdata:::cleanSpaces(format)
    if(length(format)>1) stop("Only one format can be specified.")
    if(!format %in% c("r","flextable","rmd","rmd-pdf")) {
        stop("format must be one of R, flextable, rmd, or a path to a file with extension .pdf.")
    }
    
    fixUnder <- ifelse(format%in%c("rmd","rmd-pdf"),
                       function(x)gsub("\\_","\\\\_",x),
                       identity)
    
    if( !missing(file.mod) && !is.null(file.mod) ){
        model <- modelPaths(file.mod)
    } else if(!is.null(info.source$dataCreate$model)){
        model <- modelPaths(info.source$dataCreate$model)
    }
    
### this is a header
    string.caption <- paste0("Base model parameters"
                            ," (Model ",fixUnder(model$run),")"
                             )


    footnotes <- c(footnotes,
                   "* parameter was estimated in the log domain and back-transformed for clarity.",
                   "RSE: Relative Standard Error on the scale where the parameter was estimated.")

    if(!is.null(script)){
        footnotes <- c(footnotes,sprintf("Source: %s",fixUnder(script)))
    }
    if(!is.null(model)){
        footnotes <- c(footnotes,sprintf("Model: %s",fixUnder(model$label)))
    }

    
##### subset parameters
    if("symbol" %in% colnames(paramtbl)){
        if( !is.null(drop) ){
            paramtbl <- paramtbl[!symbol%in%drop]
        }
        if( !is.null(include) ){
            paramtbl <- paramtbl[symbol%in%include]
        }

        if(!is.null(drop.pattern)){
            paramtbl <- paramtbl[!grepl(pattern=drop.pattern,symbol,fix=FALSE)]
        }

        if(!is.null(include.pattern)){
            paramtbl <- paramtbl[!grepl(pattern=drop.pattern,symbol,fix=FALSE)]
        }
        
        if( is.logical(include.fix) && isFALSE(include.fix) ){
            paramtbl <- paramtbl[FIX==0|symbol%in%include]
        }
        
        if( !is.logical(include.fix) && tolower(include.fix)=="ifnotzero" ){
            paramtbl <- paramtbl[FIX==0|est!=0|symbol%in%include]
        }
    }

    
    if(format=="r"){

        paramtbl <- paramtbl[,.(
            Panel=panel.label,
            "Parameter"=par.name,
            "Label"=tab.lab,
            "Estimate (RSE%) [CV% or Corr%]"=tab.est,
            "95% Confidence Interval"=CI
        )]

        lapply(footnotes,message)
        return(kable(paramtbl,format="pipe"))
    }


    

    if(format=="flextable"){

        paramtbl <- paramtbl[,.(
            "  "=par.name,
            " "=tab.lab,
            "Estimate (RSE%) [CV% or Corr%]"=tab.est,
            "95% Confidence Interval"=CI,
            panel.label)]

        paramtbl2 <- paramtbl |>
            dplyr::group_by(panel.label) ## |>
        ## slice(1, 2) |>
        ## select(-panel.label)

        ##as_flextable(hide_grouplabel = TRUE)
        ft <- as_flextable(paramtbl2,hide_grouplabel = TRUE) ##|> autofit()

        ft <- theme_vanilla(ft)
        ft <- add_footer_lines(ft, footnotes)
        ft <- color(ft, part = "footer", color = "#666666")
        ft <- fontsize(ft, part = "footer", size=10)
        ft <- align(ft, part="footer", align = "left")
        ft <- line_spacing(ft, space = 1, part = "footer")
        
        return(ft)
        
    }



    if(format%in%c("rmd","rmd-pdf")){

        ## 
        nmbrows <- paramtbl[,.N,keyby=.(panel.label)]
        nmbrows[,start:=cumsum(shift(N,1,fill=0))+1]
        nmbrows[,end:=cumsum(N)]
        
        paramtbl2 <- paramtbl[,.(
            "  "=parameter.ltx,
            " "=tab.lab.ltx,
            "Estimate (RSE\\%)\\newline[CV\\% or Corr\\%]"=tab.est.ltx,
            "95\\% Confidence Interval"=CI)]

        
#### configure column justification and sizes. The widths are not automated.
        paramtbl2 <- 
            paramtbl2 |>
            knitr::kable(
                       format = "latex",
                       align = paste0("ll",paste(rep("c",times=(ncol(paramtbl2)-2)),collapse = "")),
                       caption = string.caption,
                       ## longtable=T,
                       booktabs=T, escape=F) |> 
                                        #col.names = gsub("Description", " ", names(paramtbl))) |>
            kable_styling(full_width = T,
                          font_size = 7.5,  latex_options = "HOLD_position") |>
            column_spec(1, width="4em")|>
            column_spec(2, width = "26em") |>
            column_spec(3, width = "12em")

        
        ## for(I in 1:nrow(dt.panel)){
        for(I in 1:nrow(nmbrows)){
            paramtbl2 <- 
                nmbrows[I,pack_rows(paramtbl2,panel.label, start, end)]
        }

        

### Footnotes

        
        pars.ltx <- paramtbl2 |>
            add_footnote(label=footnotes,notation="none",escape=FALSE)


        if(format=="rmd") return(pars.ltx)
        
    }

    if(format=="rmd-pdf"){
        ## "\\usepackage[margin=1in]{geometry}",
        latexStandAlone(pars.ltx,file.pdf=file.pdf,
                        usepackage=cc("geometry:margin=1in",
                                      booktabs,float,tabu,longtable
                                      ))
        ## return path to output?
    }

}
