##' Print parameter table to console, flextable, latex, or (latex) pdf file
##' @param pars A parameter table as generated by
##'     `NMwork::createParameterTable()`.
##' @param engine "kable", "pmtables" or "flextable".
##' @param format A format like "tex" or "pdf" for a preview or a file name for
##'     saving a file. What formats are available depends on `engine`.
##' @param footnotes Additional footnotes to include. Footnotes about theta
##'     transformations, abbreviations, and source paths will automatically be
##'     included.
##' @param script Path to source code to include in source code.
##' @param file.mod Path to Nonmem control stream. Normally when `pars` was
##'     created with `createParameterTable()`, this is not needed because `pars`
##'     will contain this information already. If so, file.mod should only be
##'     used in cases where modifications to the original parameter table are
##'     being performed to generate new ones.
##' @param include.fix Either a logical or "NotZero". `TRUE` means fixed
##'     parameters are not filtered out, `FALSE` means they are filtered out,
##'     "NotZero" means they are only kept if not equal to zero.
##' @param include A character vector of symbol values to include. All else will
##'     be dropped.
##' @param include.pattern A regular expression run on the `symbol` column. What
##'     matches will be kept.
##' @param drop A character vector of symbol values to drop. All else will be
##'     kept.
##' @param drop.pattern A regular expression run on the `symbol` column. What
##'     matches will be dropped.
##' @param include.fix Either a logical or "NotZero". `TRUE` means fixed
##'     parameters are not filtered out, `FALSE` means they are filtered out,
##'     "NotZero" means they are only kept if not equal to zero.
##' @param caption If supplied, this text will be added to a simple model naming
##'     string, based on the `file.mod` file name.
##' @param ci The default ("cov") is to attempt to extract parameter estimation
##'     uncertainty from a succesful covariate step. To use a bootstrap estimate
##'     instead,
##' @param rse.cov Include relative standard error estimate based on covariate
##'     step? Default is TRUE if source=="cov" and FALSE if not.
##' @param label.pmtables If `engine=="pmtables"`, a latex label is needed. Like
##'     label.pmtables="tab:myfirsttable".
##' @details kable: for rmd and rmd-latex: can't get longtable to work with
##'     footnotes. Currently not using footnotes.
##'
##' pmtables is only available if the package called pmtables is
##' installed. pmtables is not available on CRAN, at the time of writing
##' this. It can be installed from MPN.
##' @examples
##' file.mod <- system.file("nonmem/xgxr134.mod",package="NMwork")
##' pars <- createParameterTable(file.lst=file.mod,
##'                   args.ParsText=list(format="%idx; %symbol ; %label [%unit] ; %trans",
##'                                      format.sigma="%symbol - %label "))
##' printParameterTable(pars=pars,format="R")
##' printParameterTable(pars=pars,format="rmd")
##' @import data.table
##' @import flextable
##' @import kableExtra
##' @importFrom fs file_show
##' @importFrom dplyr group_by
##' @export

## TODO make selection dependent on boot/cov

## TODO column names dependent on rse.cov

printParameterTable <- function(pars,engine="kable",format,footnotes=NULL,script=NULL,file.mod,include,include.pattern,drop,drop.pattern,include.fix,caption,ci="cov",rse.cov=TRUE,label.pmtables) {

    if(missing(drop)) drop <- NULL
    if(missing(drop.pattern)) drop.pattern <- NULL
    if(missing(include)) include <- NULL
    if(missing(include.fix)) include.fix <- TRUE
    if(missing(include.pattern)) include.pattern <- NULL
    
    ##partab <- readRDS(file.rds)
    partab <- copy(pars)
    info.source <- NMinfo(partab)
    model <- NULL

### only one format at a time supported
    
    if(missing(format)) format <- NULL

    if(length(engine)>1) stop("Only one engine can be used at a time")

    dt.conf <- data.table(
        engine = tolower(NMdata:::cleanSpaces(engine)))
    if(!dt.conf$engine %in% c("kable","pmtables","flextable")) stop("engine must be either kable, flextable, or pmtables.")

    if(is.null(format)){
        format <- switch(dt.conf$engine,
                         pmtables="latex",
                         kable="r",
                         flextable="ft")
    }
    dt.conf$format <- format
    rm(format)
    
    ## avoid pmtables requirement for function/packge    
    if(dt.conf$engine=="pmtables"){
        loadres <- requireNamespace("pmtables",quietly=TRUE)
        if(!loadres) {
            message("pmtables not found. Please install pmtables from MPN to use engine=\"pmtables\". Switching to engine=\"kable\".")
            dt.conf$engine <- "kable"
        }
    }

    
    dt.conf[
       ,format := NMdata:::cleanSpaces(format,double=FALSE)][
       ,file.out := NA_character_][
       ,view := FALSE]

    
    
    dt.conf[!grepl("\\.",NMdata:::cleanSpaces(format))
           ,`:=`(format = tolower(NMdata:::cleanSpaces(format)),
                 view = TRUE)
            ]
    dt.conf[grepl("\\.",NMdata:::cleanSpaces(format)),
            `:=`(file.out = format,
                 format=fnExtension(format)
                 )
            ]


### format :=  code format. For a pdf, it's tex
### format.out :=  output file format. For a pdf, it's pdf
    dt.conf[,format.out := format]
    dt.conf[format=="pdf",format := "tex"]

    dt.conf[tolower(NMdata:::cleanSpaces(format))%in%c("tex","latex"),
            format := "latex"]

    dt.conf[tolower(NMdata:::cleanSpaces(format.out))%in%c("tex","latex"),
            format.out := "tex"]

    ## I don't remember where this is coming from. If format="ft", let's return the flextable object.
## dt.conf[tolower(NMdata:::cleanSpaces(format.out))%in%c("ft"),
    ##         format.out := "html"]

### set tempfile for pdf and maybe others.
    dt.conf[view==TRUE&format.out!="tex",file.out := tempfile(fileext=sprintf(".%s",format.out))]


### from here, only one format and only one file.mod supported
    if(length(dt.conf$format)>1) stop("Only one format can be specified.")

    fixUnder <- ifelse(dt.conf$format%in%c("latex"),
                       function(x)gsub("\\_","\\\\_",x),
                       identity)

    if( !missing(file.mod) && !is.null(file.mod) ){
        model <- modelPaths(file.mod)
    } else if(!is.null(info.source$dataCreate$model)){
        model <- modelPaths(info.source$dataCreate$model)
    }

### this is a header
    string.caption <- paste0("Model: ",fixUnder(model$run),".")
    if(!missing(caption)){
        string.caption <- paste(paste(caption,collapse=" ")
                               ,string.caption,
                                sep=". "
                                )
    }


##### subset parameters
    if("symbol" %in% colnames(partab)){
        if( !is.null(drop) ){
            partab <- partab[!symbol%in%drop]
        }
        if( !is.null(include) ){
            partab <- partab[symbol%in%include]
        }

        if(!is.null(drop.pattern)){
            partab <- partab[!grepl(pattern=drop.pattern,symbol,fix=FALSE)]
        }

        if(!is.null(include.pattern)){
            partab <- partab[!grepl(pattern=drop.pattern,symbol,fix=FALSE)]
        }
        
        if( is.logical(include.fix) && isFALSE(include.fix) ){
            partab <- partab[FIX==0|symbol%in%include]
        }
        
        if( !is.logical(include.fix) && tolower(include.fix)%in%c("ifnotzero", "notzero") ){
            partab <- partab[FIX==0|est!=0|symbol%in%include]
        }
    }

    ## footnote characters are *, **, *** etc
    chars.fnotes <-
        sapply(1:10,function(x)paste(rep(x="*",x),collapse=""))
    partab[par.type=="THETA"&trans%in%c("log","logit"),trans.fnchar:=chars.fnotes[.GRP],by=trans]

    partab[,row:=.I]
    partab[par.type=="THETA"&trans%in%c("log","logit"),
           parameter.ltx:=sub("\\$ *$",paste0("\\{\\}\\^\\{",trans.fnchar,"\\}\\$"),parameter.ltx),by=row]
    partab[par.type=="THETA"&trans%in%c("log","logit"),
           parameter:=paste0(parameter,trans.fnchar)]
    partab[par.type=="THETA"&trans%in%c("log","logit"),
           par.name:=paste0(par.name,trans.fnchar)]


    footnotes.trans <- unique(partab[!is.na(trans.fnchar)],by="trans")[,
                                                                       sprintf("%s Parameter was estimated in the %s domain. Estimate and CI presented on physiological scale.",trans.fnchar,trans)]

    footnotes <- c(footnotes,
                   footnotes.trans,
                   "CI: Confidence Interval based on Nonmem Covariance step.",
                   "CV: Coefficient of Variation for log-normal distributed random effects.",
                   "Corr: Correlation.",
                   "RSE: Relative Standard Error on the scale where the parameter was estimated.")
    if(!is.null(script)){
        footnotes <- c(footnotes,sprintf("Source: %s",fixUnder(script)))
    }
    if(!is.null(model)){
        footnotes <- c(footnotes,sprintf("Model: %s",fixUnder(model$label)))
    }

### add columns for reporting
    partab <- addEstFormat(pars=partab,rse.cov=rse.cov)
    partab[,CI:=switch(ci,
                       cov=tab.CI,
                       boot=tab.CI.boot,
                       none="")]

    ## sorting must be done on partab from which nmbrows is generated.
    setorder(partab,panel,i,j)
    
    if(dt.conf$engine=="kable"&& dt.conf$format=="r"){
        partab2 <- partab[,.(
            "Parameter"=par.name,
            "Label"=tab.lab,
            "Est [CV% or Corr%] (RSE%)"=tab.est,
            "95% CI"=CI,
            Panel=panel
        )]

    } else {

### would be better to have one column selection and namoing for kable and
### pmtables. So far partab1 is for pmtables, partab2 is for kable.
        
        partab1 <- partab[,.(
            parameter.ltx,
            tab.lab.ltx,
            tab.est.ltx,
            CI,
            panel.label)]
        
        partab2 <- partab[,.(
            "  "=if(dt.conf$format=="latex") parameter.ltx else par.name,
            " "=if(dt.conf$format=="latex") tab.lab.ltx else tab.lab ,
            "Estimate (RSE%)\\newline[CV% or Corr%]"=
                if(dt.conf$format=="latex") tab.est.ltx else tab.est ,
            "95% Confidence Interval"=CI,
            panel.label)]

        partab.ft <- partab[,.(
            "  "=par.name,
            " "=tab.lab ,
            "Estimate (RSE%) [CV% or Corr%]"= tab.est ,
            "95% Confidence Interval"=CI,
            panel.label)]


        if(dt.conf$format=="latex"){
            ## colnames(partab2) <- latexify(colnames(partab2))
            cnames <- copy(colnames(partab2))
            cnames[!grepl("^ *$",cnames)] <- latexify(cnames[!grepl("^ *$",cnames)])
            colnames(partab2) <- cnames
        }
    }


    if(dt.conf$engine=="kable"){
### not sure what formats are supported. At least latex, and html.

        if (dt.conf$format=="r"){
            
            silent <- lapply(footnotes,message)
            return(
                kable(partab2,format="pipe")
            )
            
        }
        
        ##
        nmbrows <- partab2[,.N,keyby=.(panel.label)]
        nmbrows[,start:=cumsum(shift(N,1,fill=0))+1]
        nmbrows[,end:=cumsum(N)]
        partab2 <- select(partab2,-panel.label)

        
#### configure column justification and sizes. The widths are not automated.
        partab2 <-
            partab2 |>
            knitr::kable(
                       ## format = "latex",
                       format = dt.conf$format, 
                       align = paste0("ll",paste(rep("c",times=(ncol(partab2)-2)),collapse = "")),
                       caption = string.caption,
                       ## longtable=T,
                       booktabs=T, escape=F) |>
                                        #col.names = gsub("Description", " ", names(partab))) |>
            kable_styling(full_width = T,
                          font_size = 7.5,  latex_options = "HOLD_position") |>
            column_spec(1, width="4em")|>
            column_spec(2, width = "26em") |>
            column_spec(3, width = "12em")

        
        ## for(I in 1:nrow(dt.panel)){
        for(I in 1:nrow(nmbrows)){
            partab2 <- 
                nmbrows[I,pack_rows(partab2,panel.label, start, end)]
        }

### Footnotes
        pars.ltx <- partab2 |>
            add_footnote(label=footnotes,notation="none",escape=FALSE)

        
### this is for format==latex
        if(dt.conf$format.out=="tex"){
            if(is.na(dt.conf$file.out)) {
                return(pars.ltx)
            } else {
                NMsim:::writeTextFile(pars.ltx,file=dt.conf$file.out)
                return(invisible(dt.conf$file.out))
            }
        }

        if(dt.conf$format.out=="pdf"){
                                        # if(is.null(file.pdf)) file.pdf <- tempfile(fileext=".pdf")
            ## "\\usepackage[margin=1in]{geometry}",
            latexStandAlone(pars.ltx,file.pdf=dt.conf$file.out,
                            usepackage=cc("geometry:margin=1in",
                                          booktabs,float,tabu,longtable
                                          ))
            if(dt.conf$view) file_show(dt.conf$file.out)
            ## return path to output?
            return(dt.conf$file.out)
        }
        return(partab2)
    }

    if(dt.conf$engine=="flextable"){
        
        loadres <- requireNamespace("ftExtra",quietly=TRUE)
        if(!loadres) {
            message("ftExtra not found. Flextable rows are not grouped with headers according to panel column.")
        }


        partab.ft <- partab.ft |>
            dplyr::group_by(panel.label) ## |>
        ## slice(1, 2) |>
        ## select(-panel.label)
        
        ##as_flextable(hide_grouplabel = TRUE)
        ft <- as_flextable(partab.ft,hide_grouplabel = TRUE) 
        ft <- theme_vanilla(ft)
        ft <- add_footer_lines(ft, footnotes)
        ft <- color(ft, part = "footer", color = "#666666")
        ft <- fontsize(ft, part = "footer", size=10)
        ft <- align(ft, part="footer", align = "left")
        ft <- line_spacing(ft, space = 1, part = "footer")
        ft <- autofit(ft)

        
        if(!is.na(dt.conf$file.out)){
            res <- switch(dt.conf$format.out,
                          docx=save_as_docx(ft,path=dt.conf$file.out),
                          html=save_as_html(ft,path=dt.conf$file.out),
                          png=save_as_image(ft,path=dt.conf$file.out),
                          pptx=save_as_pptx(ft,path=dt.conf$file.out)
                          )
            
        }



        if(dt.conf$view){
            return(ft)
        } # else {
        if(dt.conf$format=="ft") return(ft)
        return(dt.conf$file.out)
        ##      return(invisible(ft))
        
    }


    if(dt.conf$engine=="pmtables"){
        ## formats: latex, pdf, latex-pdf?

        loadres <- requireNamespace("pmtables",quietly=TRUE)
        if(!loadres) {
            stop("to use the pmtables format, pmtables must be installed. Find it on MPN.")
        }
        
        pars.ltx = 
            partab1 |>
            pmtables::st_new() |>
            pmtables::st_panel("panel.label") |>
            ## tab.lab.ltx is " "
            pmtables::st_center("tab.lab.ltx"= pmtables::col_ragged(6.5)) |>
            ## pmtables::cols_align(.r="tab.est.ltx,CI") |> 
            pmtables::st_blank("parameter.ltx","tab.lab.ltx") |>
            pmtables::st_rename("Estimate (RSE\\%)...[CV\\% or Corr\\%]" = "tab.est.ltx",
                                "95\\% Confidence Interval" = "CI") 
        
        if(!is.null(footnotes)){
            for(fn in footnotes) pars.ltx <- pmtables::st_notes(pars.ltx,fn)
        }
        ## st_notes("$^*$Parameter was estimated in the log-domain and back-transformed for clarity") |>
        ##             st_notes("Abbreviations: RSE = relative standard error (on the scale where the parameter was estimated)") |>
        ##             st_notes(paste0("Model: ", model$mod)) |>
        pars.ltx <- pars.ltx |> pmtables::st_noteconf(type = "minipage", width = 1) 

        pars.ltx <- 
            pars.ltx |>
            pmtables::stable_long(lt_cap_text=string.caption,lt_cap_label = label.pmtables)
        
        if( dt.conf$format.out=="tex") {
            ## create latex code. Don't compile.
            
            if(is.na(dt.conf$file.out)){
                res <- pars.ltx # |>
                                        # paste(collapse="\n") |>
                ##cat(res,collapse="\n")
            } else {
                res <- pars.ltx |>
                    paste(collapse="\n") |>
                    NMsim:::writeTextFile(file=dt.conf$file.out)
            }

            return(res)
        }


        if( dt.conf$format.out=="pdf" ){
            ## Creating pdf in named location. 
            ## This used to be format=="rmd-pdf"
            
            ## What is being returned?
            res <-
                pmtables::st2pdf(x=pars.ltx,dir = dirname(dt.conf$file.out), stem = fnExtension(basename(dt.conf$file.out), ""))
            if(dt.conf$view) file_show(dt.conf$file.out)
            return(res)
        }

    }
}
